version: '3.8'

services:
  golang-demo:
    build:
      context: .
    volumes:
      - ./:/demo
    ports:
      - "8080:8080"
    environment:
      - DB_ENDPOINT=postgres
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASS=demo1111
      - DB_PORT=5432
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - golang-demo
    networks:
      - backend

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: demo1111
    volumes:
      - pgdata:/var/lib/postgresql/data  # AN (18/12): sudo docker volume create pgdata
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
    external: true